name: CI/CD

on:
  push:
    branches: [ main ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: src/ArmTypeGenerator

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --version-suffix $GITHUB_RUN_NUMBER --output release
    - name: Archive Release
      uses: papeloto/action-zip@v1
      with:
        files: release/
        dest: ArmTypeGenerator.zip
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/ArmTypeGenerator.zip

  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --version-suffix $GITHUB_RUN_NUMBER --output release
    - name: Archive Release
      uses: papeloto/action-zip@v1
      with:
        files: release/
        dest: ArmTypeGenerator.zip
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ArmTypeGenerator.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
