name: CI/CD

on:
  push:
    branches: [ main ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: src/ArmTypeGenerator

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish win version
      run: dotnet publish --configuration Release --os win --no-restore --version-suffix $GITHUB_RUN_NUMBER --output ${{ github.workspace }}/release
    - name: Publish linux version
      run: dotnet publish --configuration Release --os linux --no-restore --version-suffix $GITHUB_RUN_NUMBER --output ${{ github.workspace }}/release      
    - name: Zip win version
      uses: papeloto/action-zip@v1
      with:
        files: release/win-x64/
        dest: ArmTypeGenerator_win-x64.zip
    - name: Zip win version
      uses: papeloto/action-zip@v1
      with:
        files: release/linux-x64/
        dest: ArmTypeGenerator_linux-x64.zip        
    - name: upload artifacts for debugging
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/*.zip

  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish win version
      run: dotnet publish --configuration Release --os win --no-restore --version-suffix $GITHUB_RUN_NUMBER --output ${{ github.workspace }}/release
    - name: Publish linux version
      run: dotnet publish --configuration Release --os linux --no-restore --version-suffix $GITHUB_RUN_NUMBER --output ${{ github.workspace }}/release      
    - name: Zip win version
      uses: papeloto/action-zip@v1
      with:
        files: release/win-x64/
        dest: ArmTypeGenerator_win-x64.zip
    - name: Zip win version
      uses: papeloto/action-zip@v1
      with:
        files: release/linux-x64/
        dest: ArmTypeGenerator_linux-x64.zip    
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ArmTypeGenerator_win-x64.zip,ArmTypeGenerator_linux-x64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
